# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: DockerBuildPush
  displayName: 'Buld and Push Docker Image'
  jobs:
  - job: DockerPushJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'costocksregistry'
        repository: 'corag-frontend'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'